"""Vector storage engine over versioned GeoParquet collections."""

from ocs_storage_exploration.storage.vector.collection import (
    DEFAULT_CRS,
    GEOPARQUET_SCHEMA_VERSION,
    MAXIMUM_RESERVATION_ATTEMPTS,
    CollectionEntry,
    ParquetSource,
    VectorCollectionPointer,
    VectorCollectionStore,
    VectorReadHandle,
    VectorTableSchema,
    VectorVersionReservation,
    build_frame_from_geojson,
    crs_identifier,
    frame_bounding_box,
    require_crs,
    same_crs,
    validate_feature_collection,
)
from ocs_storage_exploration.storage.vector.ingest import (
    VectorIngestPlan,
    build_vector_ingest_plan,
    ingest_vector_file,
    open_vector_file,
)
from ocs_storage_exploration.storage.vector.predicates import (
    WhereClause,
    build_filters,
    build_prefix_filter,
    coerce_clause_value,
    is_prefix_value,
    parse_where,
)

__all__ = [
    "DEFAULT_CRS",
    "GEOPARQUET_SCHEMA_VERSION",
    "MAXIMUM_RESERVATION_ATTEMPTS",
    "CollectionEntry",
    "ParquetSource",
    "VectorCollectionPointer",
    "VectorCollectionStore",
    "VectorIngestPlan",
    "VectorReadHandle",
    "VectorTableSchema",
    "VectorVersionReservation",
    "WhereClause",
    "build_filters",
    "build_frame_from_geojson",
    "build_prefix_filter",
    "build_vector_ingest_plan",
    "coerce_clause_value",
    "crs_identifier",
    "frame_bounding_box",
    "ingest_vector_file",
    "is_prefix_value",
    "open_vector_file",
    "parse_where",
    "require_crs",
    "same_crs",
    "validate_feature_collection",
]
